package cn.java.note.parser.webxml;


public class WebXml文件的模板 {
/*
     	 	<web-app>
    	 		<absolute-ordering></absolute-ordering>
    	 		<ordering></ordering>
    	 		<context-param>
					<param-name></param-name>
					<param-value></param-value>
				</context-param>
				<display-name></display-name>				
				<distributable></distributable>
				<error-page>
					<error-code></error-code>
					<exception-type></exception-type>
					<location></location>
				</error-page>
				<filter>
					<description></description>
					<display-name></display-name>
					<filter-class></filter-class>
					<filter-name></filter-name>
					<icon>
						<small-icon></small-icon>
					</icon>
					<async-supported></async-supported>
					<init-param>
						<param-name></param-name>
						<param-value></param-value>
					</init-param>
				</filter>
				<filter-mapping>
					<filter-name></filter-name>
					<servlet-name></servlet-name>
					<url-pattern></url-pattern>
					<dispatcher></dispatcher>
				</filter-mapping>
				<listener>
					<listener-class></listener-class>
				</listener>
				<jsp-config>
					<jsp-property-group>
						<deferred-syntax-allowed-as-literal></deferred-syntax-allowed-as-literal>
				        <el-ignored></el-ignored>
				        <include-coda></include-coda>
				        <include-prelude></include-prelude>
				        <is-xml></is-xml>
				        <page-encoding></page-encoding>
				        <scripting-invalid></scripting-invalid>
				        <trim-directive-whitespaces></trim-directive-whitespaces>
				        <url-pattern></url-pattern>
				        <default-content-type></default-content-type>
				        <buffer></buffer>
				        <error-on-undeclared-namespace></error-on-undeclared-namespace>
					</jsp-property-group>
					<taglib> Servlet 2.4 后的特性
				    	<taglib-location></taglib-location>
				    	<taglib-uri></taglib-uri>
				    </taglib>
				    <taglib>
					    <taglib-location></taglib-location>
					    <taglib-uri></taglib-uri>
				    </taglib>
				</jsp-config>
				<login-config>
					<auth-method></auth-method>
					<realm-name></realm-name>
					<form-login-config>
						<form-error-page></form-error-page>
						<form-login-page></form-login-page>
					</form-login-config>
				</login-config>
				<mime-mapping>
					<extension></extension>
					<mime-type></mime-type>
				</mime-mapping>
				<security-constraint>
					<auth-constraint>
						<role-name></role-name>
						<display-name></display-name>
					</auth-constraint>
					<user-data-constraint>
						<transport-guarantee></transport-guarantee>
					</user-data-constraint>
					<web-resource-collection>
						<http-method></http-method>
					    <http-method-omission></http-method-omission>
					    <url-pattern></url-pattern>
					    <web-resource-name></web-resource-name>
					</web-resource-collection>
				</security-constraint>
				<security-role>
		        	<role-name></role-name>
		        </security-role>
		        <servlet>
		        	<init-param>
		        		<param-name></param-name>
		        		<param-value></param-value>
		        	</init-param>
		        	<init-param>
			        	<param-name></param-name>
			        	<param-value></param-value>
		        	</init-param>
		        	<jsp-file></jsp-file>
		        	<load-on-startup></load-on-startup>
		        	<run-as>
		        		<role-name></role-name>
		        	</run-as>
		        	<security-role-ref>
			        	<role-link></role-link>
			        	<role-name></role-name>
		        	</security-role-ref>
		        	<security-role-ref>
			        	<role-link></role-link>
			        	<role-name></role-name>
		        	</security-role-ref>
		        	<servlet-class></servlet-class>
			        <servlet-name></servlet-name>
			        <multipart-config>
			        	<location></location>
			        	<max-file-size></max-file-size>
			        	<max-request-size></max-request-size>
			        	<file-size-threshold></file-size-threshold>
			        </multipart-config>
			        <async-supported></async-supported>
			        <enabled></enabled>
		        </servlet>
		        <servlet-mapping>
					<servlet-name></servlet-name>
					<url-pattern></url-pattern>
				</servlet-mapping>
				<session-config>
					<session-timeout></session-timeout>
					<cookie-config>
						<name></name>
						<domain></domain>
						<path></path>
						<comment></comment>
						<http-only></http-only>
						<secure></secure>
						<max-age></max-age>
					</cookie-config>
					<tracking-mode></tracking-mode>
					<tracking-mode></tracking-mode>
				</session-config>
				<taglib> Servlet 2.4 前的特性
		        	<taglib-location></taglib-location>
		        	<taglib-uri></taglib-uri>
		        </taglib>
		        <welcome-file-list>
		        	<welcome-file></welcome-file>
		        	<welcome-file></welcome-file>
		        </welcome-file-list>
		        <locale-encoding-mapping-list>
					<locale-encoding-mapping>
						<locale></locale>
						<encoding></encoding>
					</locale-encoding-mapping>
				</locale-encoding-mapping-list>
				<post-construct>
					<lifecycle-callback-class></lifecycle-callback-class>
					<lifecycle-callback-method></lifecycle-callback-method>
				</post-construct>
				<pre-destroy>
					<lifecycle-callback-class></lifecycle-callback-class>
					<lifecycle-callback-method></lifecycle-callback-method>
				</pre-destroy>
    	 	</web-app>
 */
	public static void main(String[] args) {

	}

}
