package cn.java.note.ast;

public class Parser是自动生成的 {
	
	/**
	 * This class is responsible for parsing a Velocity
	 * template. This class was generated by JavaCC using
	 * the JJTree extension to produce an Abstract
	 * Syntax Tree (AST) of the template.
	 *
	 * Please look at the Parser.jjt file which is
	 * what controls the generation of this class.
	 *
	 * @author <a href="mailto:jvanzyl@apache.org">Jason van Zyl</a>
	 * @author <a href="mailto:geirm@optonline.net">Geir Magnusson Jr.</a>
	 * @author <a href="hps@intermeta.de">Henning P. Schmiedehausen</a>
	 * @version $Id: Parser.java 928463 2010-03-28 18:11:34Z nbubna $
	
		public class Parser implements ParserTreeConstants, ParserConstants {
			
		}
	*/
}
